# Generated by Django 5.1 on 2024-11-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
    ]
