# Generated by Django 5.1 on 2024-11-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0004_remove_blog_views_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
    ]
