# Generated by Django 5.1 on 2024-11-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0005_remove_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
