# Generated by Django 5.1 on 2024-11-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0006_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default='default text'),
        ),
    ]
