# Generated by Django 5.1 on 2024-11-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0010_blog_delete_page_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
