# Generated by Django 5.1 on 2024-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0013_like_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='keiziban_post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
