# Generated by Django 5.1 on 2024-11-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0014_keiziban_post_views_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keiziban_post',
            name='views',
        ),
    ]
