# Generated by Django 5.1 on 2024-11-26 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohara', '0017_alter_viewcount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
